# Generated by Django 4.1 on 2023-11-09 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedAnswerQuestion",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("extended_answer", "Extended Answer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HaileUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_score", models.IntegerField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("extended_answer", "Extended Answer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question_text", models.TextField()),
                ("choices", models.JSONField()),
                ("correct_choice", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("quiz_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MultipleChoiceResponse",
            fields=[
                ("response_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_correct", models.BooleanField(null=True)),
                ("selected_choice", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="haileapp.multiplechoicequestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="haileapp.haileuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="haileapp.quiz"
            ),
        ),
        migrations.CreateModel(
            name="ExtendedAnswerResponse",
            fields=[
                ("response_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_correct", models.BooleanField(null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="haileapp.extendedanswerquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="haileapp.haileuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="extendedanswerquestion",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="haileapp.quiz"
            ),
        ),
        migrations.CreateModel(
            name="ChatPrompt",
            fields=[
                ("prompt_id", models.AutoField(primary_key=True, serialize=False)),
                ("prompt_text", models.TextField()),
                ("section_from", models.CharField(max_length=100)),
                ("ai_response", models.TextField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="haileapp.haileuser",
                    ),
                ),
            ],
        ),
    ]
