# Generated by Django 4.1 on 2023-11-09 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("haileapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendedanswerquestion",
            name="question_type",
        ),
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="question_type",
        ),
    ]
