# Generated by Django 4.1 on 2023-11-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haileapp', '0003_alter_haileuser_final_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multiplechoiceresponse',
            unique_together={('user', 'question')},
        ),
    ]
