# Generated by Django 4.1 on 2023-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haileapp', '0004_alter_multiplechoiceresponse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedanswerresponse',
            name='user_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
