# Generated by Django 4.1 on 2024-01-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haileapp', '0006_haileuser_has_studied'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedanswerquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
