# Generated by Django 4.1 on 2024-01-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haileapp', '0007_extendedanswerquestion_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haileuser',
            name='current_level_of_study',
            field=models.CharField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), ('FR1', 'Faster Route Level 1'), ('FR2', 'Faster Route Level 2'), ('FR3', 'Faster Route Level 3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='haileuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('other', 'Other/Prefer Not to Say')], max_length=20, null=True),
        ),
    ]
